name: CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'

      - name: Install Python Packages
        run: poetry install --with=dev

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'

      - name: Install Python Packages
        run: poetry install --with=dev

      - name: Run Tests
        run: poetry run pytest
